// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoomRental.Dal;

#nullable disable

namespace RoomRental.Dal.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoomRental.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Period", "RoomRental.Domain.Entities.Booking.Period#BookingPeriod", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("date");

                            b1.Property<TimeOnly>("From")
                                .HasColumnType("time without time zone")
                                .HasColumnName("start_time");

                            b1.Property<TimeOnly>("To")
                                .HasColumnType("time without time zone")
                                .HasColumnName("end_time");
                        });

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_bookings_customer_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_bookings_room_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.BookingCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("kind");

                    b.Property<decimal>("Multiplier")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("multiplier");

                    b.Property<Guid?>("PricingRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_rule_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("SegmentEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("segment_end");

                    b.Property<DateTime?>("SegmentStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("segment_start");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_booking_charges");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_booking_charges_booking_id");

                    b.HasIndex("PricingRuleId")
                        .HasDatabaseName("ix_booking_charges_pricing_rule_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_booking_charges_service_id");

                    b.ToTable("booking_charges", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.BookingSlot", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("SlotStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("slot_start");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.HasKey("RoomId", "SlotStart")
                        .HasName("pk_booking_slots");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_booking_slots_booking_id");

                    b.ToTable("booking_slots", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.PricingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly>("From")
                        .HasColumnType("time without time zone")
                        .HasColumnName("from");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Multiplier")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("multiplier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<TimeOnly>("To")
                        .HasColumnType("time without time zone")
                        .HasColumnName("to");

                    b.HasKey("Id")
                        .HasName("pk_pricing_rules");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_pricing_rules_is_active");

                    b.ToTable("pricing_rules", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseHourPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_hour_price");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasIndex("Capacity")
                        .HasDatabaseName("ix_rooms_capacity");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_rooms_created_at_utc");

                    b.HasIndex("DeletedAtUtc")
                        .HasDatabaseName("ix_rooms_deleted_at_utc");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_services_created_at_utc");

                    b.HasIndex("DeletedAtUtc")
                        .HasDatabaseName("ix_services_deleted_at_utc");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RoomService", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("ServicesId")
                        .HasColumnType("uuid")
                        .HasColumnName("services_id");

                    b.HasKey("RoomId", "ServicesId")
                        .HasName("pk_room_service");

                    b.HasIndex("ServicesId")
                        .HasDatabaseName("ix_room_service_services_id");

                    b.ToTable("room_service", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.Booking", b =>
                {
                    b.HasOne("RoomRental.Domain.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_users_customer_id");

                    b.HasOne("RoomRental.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_rooms_room_id");

                    b.Navigation("Customer");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.BookingCharge", b =>
                {
                    b.HasOne("RoomRental.Domain.Entities.Booking", "Booking")
                        .WithMany("Charges")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_charges_bookings_booking_id");

                    b.HasOne("RoomRental.Domain.Entities.PricingRule", "PricingRule")
                        .WithMany()
                        .HasForeignKey("PricingRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_booking_charges_pricing_rules_pricing_rule_id");

                    b.HasOne("RoomRental.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_booking_charges_services_service_id");

                    b.Navigation("Booking");

                    b.Navigation("PricingRule");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.BookingSlot", b =>
                {
                    b.HasOne("RoomRental.Domain.Entities.Booking", "Booking")
                        .WithMany("Slots")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_slots_bookings_booking_id");

                    b.HasOne("RoomRental.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_slots_rooms_room_id");

                    b.Navigation("Booking");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RoomService", b =>
                {
                    b.HasOne("RoomRental.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_service_rooms_room_id");

                    b.HasOne("RoomRental.Domain.Entities.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_service_services_services_id");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Charges");

                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
